#!zsh
if [ $commands[fasd] ]; then # check if fasd is installed
  fasd_cache="${ZSH_CACHE:-$HOME}/fasd-init-cache"
  if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
    fasd --init auto >| "$fasd_cache"
  fi
  source "$fasd_cache"
  unset fasd_cache

  alias 2='fasd_cd -d'
fi
