#!zsh

alias y="yarn"
alias y+="yarn add"
alias yd="yarn add --dev"

export PATH="$(yarn global bin):$PATH"

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
