#!zsh

### yarn
# alias y="yarn"
# alias y+="yarn add"
# alias yd="yarn add --dev"

export PATH="$(yarn global bin):$PATH"
### yarn end

### pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

alias y="pnpm" # muscle memory
alias y+="pnpm add"
alias yd="pnpm add --save-dev"
### pnpm end
