#!zsh

alias ls="command ls -al --color"
alias x=exit
alias v="nvim"

# Use C-x C-e to edit the current command line
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

# restore emacs settings even though EDITOR=nvim
# allows e.g. \C-r for history search
set -o emacs
bindkey -e
