#!/usr/bin/env sh
[ -n "$GIT_EMAIL" ] && git config --global user.email "$GIT_EMAIL"
[ -n "$GIT_NAME" ] && git config --global user.name "$GIT_NAME"

git config --global include.path `pwd`/config/.gitconfig
git config --global core.excludesFile `pwd`/config/.gitignore
