#!/usr/bin/env sh
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0

# https://github.com/asdf-vm/asdf-nodejs#install
bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
