#!/usr/bin/env sh

# misc formulae to install
# to calculate::
#
#     brew leaves

brew install \
  cloc \
  direnv \
  gh \
  glab \
  gnupg \
  neovim \
  pipx \
  ripgrep \
  tmux \
  tree \
  universal-ctags \
  wget
# bats-core \
# exercism \
# fasd \
# gawk \
# lolcat \
# luajit-openresty \
# tmate \
