#!/usr/bin/env sh

# misc formulae to install
# to calculate::
#
#     brew leaves

brew install \
  glab \
  graphviz \
  mise \
  neovim \
  ripgrep \
  stow \
  universal-ctags
# icu4c \
# libnsl \
