#!/usr/bin/env sh
# sudo apt install chrome-gnome-shell
mkdir -p downloads
curl https://extensions.gnome.org/extension-data/caffeinepatapon.info.v37.shell-extension.zip > downloads/caffeine.zip
gnome-extensions install downloads/caffeine.zip
gnome-extensions enable caffeine@patapon.info
