#!/usr/bin/env sh
scripts/essentials
scripts/homebrew
scripts/zsh
scripts/asdf
scripts/gnome-tweak-tool
scripts/gnome-extensions
scripts/chrome
scripts/tmux
scripts/fasd
scripts/github
scripts/docker
scripts/docker-compose
scripts/fzf
scripts/ag
scripts/ctags
