#!/usr/bin/env sh
asdf plugin add nodejs
asdf plugin add yarn
asdf plugin add pnpm
asdf plugin add bun
asdf plugin add deno
asdf install nodejs lts
asdf install yarn latest
asdf install pnpm latest
asdf install deno latest
asdf install bun latest
pnpm install --global \
	neovim \
	diagnostic-languageserver \
	typescript-language-server
