#!/usr/bin/env sh

if [ $IS_LINUX ]; then

  # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
  sudo apt-get install \
    make \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev

fi

asdf plugin add python
asdf install python latest
