#!/usr/bin/env sh

# https://github.com/rbenv/ruby-build/wiki#ubuntudebianmint
sudo apt-get install autoconf bison patch build-essential rustc libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev

asdf plugin add ruby
asdf install ruby latest
asdf global ruby latest
