#!/usr/bin/env sh
# https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux
sudo apt install libwebkit2gtk-4.0-dev \
    build-essential \
    curl \
    wget \
    libssl-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev
